### ISSUE TITLE
License recognition for CSharp

### ISSUE THREAD

**Issue by reiz** [versioneye/crawl_r#27]
Many packages on Nuget only provide a link to license but no license name. During the crawling we should check if the license link is matching with a well known source. I found for example 64K license objects in our db where the url was `http://www.apache.org/licenses/LICENSE-2.0.html` and the license name was nil. I updated them all and set the name to `Apache-2.0`. This logic should be part of the Nuget crawler. Check at least for this urls: 

http://www.apache.org/licenses/LICENSE-2.0.html
https://www.apache.org/licenses/LICENSE-2.0.html
https://opensource.org/licenses/MIT

**Comment by timgluz** [comment]
Yes, it's [already implemented](https://github.com/timgluz/crawl_r/blob/add_fuzzy_matcher/lib/versioneye/crawlers/license_crawler.rb#L69) - it uses all the urls from the `licenses.json` and missing urls can be added into this file;

**Comment by reiz** [comment]
@timgluz Just merged PR #26.

**Comment by reiz** [comment]
@timgluz I just added it to the mapping. Can you check if I added it to the right file? I saw there are 3 licsense.json files.
