### ISSUE TITLE
Add cargo links

### ISSUE THREAD

**Issue by reiz** [versioneye/crawl_r#36]
@timgluz Every Rust package is available through a unique URL. 

```
https://crates.io/crates/<PACKAGE>
```

For example: 

```
https://crates.io/crates/aseprite
```

The crawler should create this links automatically so that we can display it on the VersionEye pages.

**Comment by timgluz** [comment]
OK

**Comment by reiz** [comment]
Yes. If possible with version string.

**Comment by timgluz** [comment]
I think this issue is solved now

**Comment by reiz** [comment]
@timgluz This is fixed now. Good Job 👍
