### ISSUE TITLE
Authors for Rust

### ISSUE THREAD

**Issue by reiz** [versioneye/crawl_r#37]
@timgluz Why we don't have Author information for Rust packages? Is it not included in the REST API?

**Comment by reiz** [comment]
@timgluz On this page the Author is listed: https://crates.io/crates/aseprite.

**Comment by timgluz** [comment]
We collect owners of packages - those are people who own, maintain and release the package.
Authors seems to be people from git commits and they belong to version/release, but not to package.

**Comment by timgluz** [comment]
We can collect also authors, but it is more noisy - some has name, alias, email; some has only email;

**Comment by timgluz** [comment]
ok, i can add it - it just a bit more preprocessing than owners api

here's example output: 
`curl "https://crates.io/api/v1/crates/nanomsg/0.6.2/authors?api_key=$CRATES_KEY" | jq`

```json
{
  "meta": {
    "names": [
      "Benoît Labaere <benoit.labaere@gmail.com>",
      "Chip Collier",
      "Dan Burkert",
      "Daniel Fagnan <dnfagnan@gmail.com>",
      "David C. Bishop",
      "Dennis Lawler",
      "Jason E. Aten",
      "Zachary Tong"
    ]
  },
  "users": []
}
```

**Comment by reiz** [comment]
@timgluz OK. Let's store authors & maintainers in the developer collection: https://github.com/versioneye/versioneye-core/blob/master/lib/versioneye/models/developer.rb.

**Comment by reiz** [comment]
@timgluz Added some comments here: https://github.com/versioneye/versioneye-core/commit/c1b5b2f83c7caf685ac7667e6a48a02b387c296c

**Comment by reiz** [comment]
@timgluz fixed with the last commit.
