### ISSUE TITLE
Elixir crawlers with API Key

### ISSUE THREAD

**Issue by reiz** [versioneye/crawl_r#48]
The Hex API is limited. We need an API key and the Hex crawler needs to be refactored that they that it's using an API key for every request to the Hex API. If possible the crawler should check how many requests remain and wait for N minutes if the rate limit is used of.

**Comment by timgluz** [comment]
I checked, using API token doesn't increase API limits.

But here's a way to acquire API token:

```
curl -u "timgluz" -X POST -H "Content-Type: application/json" -d '{"name": "test_client"}' https://hex.pm/api/keys

curl -vvvv -H "Authorization: $HEX_TOKEN" https://hex.pm/api
```

**Comment by reiz** [comment]
@timgluz OK. We are checking now the rate limit. That's good enough for now.
