### ISSUE TITLE
Tests are slow & breaking

### ISSUE THREAD

**Issue by reiz** [versioneye/crawl_r#51]
The complete test suite quiet slow and some tests are failing. I guess the tests for bower are slow. Please review & refactor them. Make the test work again and if possible improve the speed.

**Comment by timgluz** [comment]
oki, i will check into failing tests - not sure i can make it faster;

**Comment by reiz** [comment]
Hi @timgluz fixing the failing tests has priority. 
I guess the bower test is very slow because it's using a GitHub repository with many tags. Using another repo with less tags would speed up the test suite.

**Comment by timgluz** [comment]
tests are fixed now with #58 - Bower specs were slow because they made real github request and those request were not using any Github key - i wrapped it into VCR, but there're other slow tests;

**Comment by timgluz** [comment]
I think to find slow tests, i need to change the view of testrunner, which could show more detailed information.

**Comment by reiz** [comment]
@timgluz Just merged it. Tests are running on CircleCI now. https://circleci.com/gh/versioneye/crawl_r/165

**Comment by timgluz** [comment]
Ok, i will review it tomorrow morning - i think there's some difference how my Github tokens are initialized.

**Comment by timgluz** [comment]
Yep, i was able to replicate failing tests, those are fixed now;
