### ISSUE TITLE
[refactor] Api for CpanCrawler has changed

### ISSUE THREAD

**Issue by timgluz** [versioneye/crawl_r#57]
I found out that the url of API for CPAN crawler has been changed and old url doesnt work anymore.

ToDO:

* change url
* check has data from API changed
* update response fixtures in the `spec/fixtures/files/cpan`
* run crawler for extended period of time and check does scrolling work

API docs: https://github.com/metacpan/metacpan-api/blob/master/docs/API-docs.md

**Comment by timgluz** [comment]
I started to digg into it - sadly, i cant assigned to me;

**Comment by timgluz** [comment]
solution is in the PR #60

**Comment by reiz** [comment]
I just merged it.

**Comment by reiz** [comment]
@timgluz I just pulled the fresh code. Now reviewing again in my locale editor. I guess I will have some little refactoring and questions.
