### ISSUE TITLE
No Cpan dependencies

### ISSUE THREAD

**Issue by reiz** [versioneye/crawl_r#68]
I refactored the Cpan crawler. Remove all Threads and using RabbitMQ directly. In generell everything seems to work. But somehow there is not a single Perl dependency in the db. Even not after 2000 packages have been crawled. Maybe a bug?

**Comment by reiz** [comment]
By the way, here are the [changes](https://github.com/versioneye/crawl_r/commit/96587071a4fd03071b759709731426dae000c296).

**Comment by reiz** [comment]
Now I'm logging out `release_doc[:dependency]` and somehow it has always the value `[]`. Maybe the dependencies are documented somewhere else?

**Comment by timgluz** [comment]
old packages doesn't have dependencies - if you crawl packages from 2 days
ago, then you can see dependencies. I don't know why it is that, but even
their official pages doesn't show dependency details for very old packages.

**Comment by reiz** [comment]
@timgluz OK. Then it is how it is.
