### ISSUE TITLE
Check why Nuget crawler misses latest versions for System packages

### ISSUE THREAD

**Issue by timgluz** [versioneye/crawl_r#73]
System.Linq, System.Collections are still stuck at `4.0.11`, but they should have `4.3.0`

**Comment by timgluz** [comment]
TODO:

* fix errors in the logs;
* look up the collections including missing versions, and crawl them again
* to test run

**Comment by timgluz** [comment]
I fixed a couple of crawler issues; 

i noticed that there were quite many `request timeouts` in the log files, seems it makes more sense to re-crawl everything, so it could add missing releases;

**Comment by timgluz** [comment]
I am still doing test run to catch any other issue;

**Comment by reiz** [comment]
The new crawler is running on production.
