### ISSUE TITLE
License field has been moved for Rust Crates;

### ISSUE THREAD

**Issue by timgluz** [versioneye/crawl_r#76]
I got email notification for a Rust package i follow and i noticed it is now missing license details.

I digged into the problem and i noticed that the response model from the API has been changed - they moved all the licenses onto versions; 

```
curl https://crates.io/api/v1/crates/tokio-core?api_key=XYZ | jq
```

**Comment by timgluz** [comment]
Also add error-loggers to catch similar cases in the future

**Comment by reiz** [comment]
Crawler has been executed we recrawl method on production.
